//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiJingCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YiJingCore.Resources.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關於.
        /// </summary>
        internal static string ChineseAbout {
            get {
                return ResourceManager.GetString("ChineseAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 變.
        /// </summary>
        internal static string ChineseChange {
            get {
                return ResourceManager.GetString("ChineseChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日.
        /// </summary>
        internal static string ChineseCharDay {
            get {
                return ResourceManager.GetString("ChineseCharDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時.
        /// </summary>
        internal static string ChineseCharHour {
            get {
                return ResourceManager.GetString("ChineseCharHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 閏.
        /// </summary>
        internal static string ChineseCharLeap {
            get {
                return ResourceManager.GetString("ChineseCharLeap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月.
        /// </summary>
        internal static string ChineseCharMonth {
            get {
                return ResourceManager.GetString("ChineseCharMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年.
        /// </summary>
        internal static string ChineseCharYear {
            get {
                return ResourceManager.GetString("ChineseCharYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 八.
        /// </summary>
        internal static string ChineseEight {
            get {
                return ResourceManager.GetString("ChineseEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 十一.
        /// </summary>
        internal static string ChineseEleven {
            get {
                return ResourceManager.GetString("ChineseEleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 五.
        /// </summary>
        internal static string ChineseFive {
            get {
                return ResourceManager.GetString("ChineseFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四.
        /// </summary>
        internal static string ChineseFour {
            get {
                return ResourceManager.GetString("ChineseFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 九.
        /// </summary>
        internal static string ChineseNine {
            get {
                return ResourceManager.GetString("ChineseNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一.
        /// </summary>
        internal static string ChineseOne {
            get {
                return ResourceManager.GetString("ChineseOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 七.
        /// </summary>
        internal static string ChineseSeven {
            get {
                return ResourceManager.GetString("ChineseSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 六.
        /// </summary>
        internal static string ChineseSix {
            get {
                return ResourceManager.GetString("ChineseSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 十.
        /// </summary>
        internal static string ChineseTen {
            get {
                return ResourceManager.GetString("ChineseTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三.
        /// </summary>
        internal static string ChineseThree {
            get {
                return ResourceManager.GetString("ChineseThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 十二.
        /// </summary>
        internal static string ChineseTwelve {
            get {
                return ResourceManager.GetString("ChineseTwelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二.
        /// </summary>
        internal static string ChineseTwo {
            get {
                return ResourceManager.GetString("ChineseTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 動.
        /// </summary>
        internal static string ChineseWordDong {
            get {
                return ResourceManager.GetString("ChineseWordDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 為.
        /// </summary>
        internal static string ChineseWordRepresent {
            get {
                return ResourceManager.GetString("ChineseWordRepresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 爻.
        /// </summary>
        internal static string ChineseWordYao {
            get {
                return ResourceManager.GetString("ChineseWordYao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 狗.
        /// </summary>
        internal static string ChineseZodiacDog {
            get {
                return ResourceManager.GetString("ChineseZodiacDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 龍.
        /// </summary>
        internal static string ChineseZodiacDragon {
            get {
                return ResourceManager.GetString("ChineseZodiacDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 馬.
        /// </summary>
        internal static string ChineseZodiacHorse {
            get {
                return ResourceManager.GetString("ChineseZodiacHorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 猴.
        /// </summary>
        internal static string ChineseZodiacMonkey {
            get {
                return ResourceManager.GetString("ChineseZodiacMonkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 牛.
        /// </summary>
        internal static string ChineseZodiacOx {
            get {
                return ResourceManager.GetString("ChineseZodiacOx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 豬.
        /// </summary>
        internal static string ChineseZodiacPig {
            get {
                return ResourceManager.GetString("ChineseZodiacPig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兔.
        /// </summary>
        internal static string ChineseZodiacRabbit {
            get {
                return ResourceManager.GetString("ChineseZodiacRabbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 羊.
        /// </summary>
        internal static string ChineseZodiacRam {
            get {
                return ResourceManager.GetString("ChineseZodiacRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鼠.
        /// </summary>
        internal static string ChineseZodiacRat {
            get {
                return ResourceManager.GetString("ChineseZodiacRat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雞.
        /// </summary>
        internal static string ChineseZodiacRooster {
            get {
                return ResourceManager.GetString("ChineseZodiacRooster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 蛇.
        /// </summary>
        internal static string ChineseZodiacSnake {
            get {
                return ResourceManager.GetString("ChineseZodiacSnake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 虎.
        /// </summary>
        internal static string ChineseZodiacTiger {
            get {
                return ResourceManager.GetString("ChineseZodiacTiger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 即時起卦.
        /// </summary>
        internal static string DivineNow {
            get {
                return ResourceManager.GetString("DivineNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隨機起卦.
        /// </summary>
        internal static string DivineRandom {
            get {
                return ResourceManager.GetString("DivineRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 辰.
        /// </summary>
        internal static string EarthlyBranchesChen {
            get {
                return ResourceManager.GetString("EarthlyBranchesChen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 丑.
        /// </summary>
        internal static string EarthlyBranchesChou {
            get {
                return ResourceManager.GetString("EarthlyBranchesChou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 亥.
        /// </summary>
        internal static string EarthlyBranchesHai {
            get {
                return ResourceManager.GetString("EarthlyBranchesHai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卯.
        /// </summary>
        internal static string EarthlyBranchesMao {
            get {
                return ResourceManager.GetString("EarthlyBranchesMao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申.
        /// </summary>
        internal static string EarthlyBranchesShen {
            get {
                return ResourceManager.GetString("EarthlyBranchesShen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 巳.
        /// </summary>
        internal static string EarthlyBranchesSi {
            get {
                return ResourceManager.GetString("EarthlyBranchesSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未.
        /// </summary>
        internal static string EarthlyBranchesWei {
            get {
                return ResourceManager.GetString("EarthlyBranchesWei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 午.
        /// </summary>
        internal static string EarthlyBranchesWu {
            get {
                return ResourceManager.GetString("EarthlyBranchesWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戌.
        /// </summary>
        internal static string EarthlyBranchesXu {
            get {
                return ResourceManager.GetString("EarthlyBranchesXu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 寅.
        /// </summary>
        internal static string EarthlyBranchesYin {
            get {
                return ResourceManager.GetString("EarthlyBranchesYin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 酉.
        /// </summary>
        internal static string EarthlyBranchesYou {
            get {
                return ResourceManager.GetString("EarthlyBranchesYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 子.
        /// </summary>
        internal static string EarthlyBranchesZi {
            get {
                return ResourceManager.GetString("EarthlyBranchesZi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用生體.
        /// </summary>
        internal static string ExternalGeneratesInternal {
            get {
                return ResourceManager.GetString("ExternalGeneratesInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用克體.
        /// </summary>
        internal static string ExternalOvercomessInternal {
            get {
                return ResourceManager.GetString("ExternalOvercomessInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 土.
        /// </summary>
        internal static string FivePhasesAttributeEarth {
            get {
                return ResourceManager.GetString("FivePhasesAttributeEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火.
        /// </summary>
        internal static string FivePhasesAttributeFire {
            get {
                return ResourceManager.GetString("FivePhasesAttributeFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金.
        /// </summary>
        internal static string FivePhasesAttributeGold {
            get {
                return ResourceManager.GetString("FivePhasesAttributeGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水.
        /// </summary>
        internal static string FivePhasesAttributeWater {
            get {
                return ResourceManager.GetString("FivePhasesAttributeWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 木.
        /// </summary>
        internal static string FivePhasesAttributeWood {
            get {
                return ResourceManager.GetString("FivePhasesAttributeWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 丙.
        /// </summary>
        internal static string HeavenlyStemsBing {
            get {
                return ResourceManager.GetString("HeavenlyStemsBing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 丁.
        /// </summary>
        internal static string HeavenlyStemsDing {
            get {
                return ResourceManager.GetString("HeavenlyStemsDing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 庚.
        /// </summary>
        internal static string HeavenlyStemsGeng {
            get {
                return ResourceManager.GetString("HeavenlyStemsGeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 己.
        /// </summary>
        internal static string HeavenlyStemsJi {
            get {
                return ResourceManager.GetString("HeavenlyStemsJi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 甲.
        /// </summary>
        internal static string HeavenlyStemsJia {
            get {
                return ResourceManager.GetString("HeavenlyStemsJia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 癸.
        /// </summary>
        internal static string HeavenlyStemsKui {
            get {
                return ResourceManager.GetString("HeavenlyStemsKui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 壬.
        /// </summary>
        internal static string HeavenlyStemsRen {
            get {
                return ResourceManager.GetString("HeavenlyStemsRen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戊.
        /// </summary>
        internal static string HeavenlyStemsWu {
            get {
                return ResourceManager.GetString("HeavenlyStemsWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 辛.
        /// </summary>
        internal static string HeavenlyStemsXin {
            get {
                return ResourceManager.GetString("HeavenlyStemsXin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乙.
        /// </summary>
        internal static string HeavenlyStemsYi {
            get {
                return ResourceManager.GetString("HeavenlyStemsYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水地比.
        /// </summary>
        internal static string HexagramBi {
            get {
                return ResourceManager.GetString("HexagramBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 山火賁.
        /// </summary>
        internal static string HexagramBi_ShanHuo {
            get {
                return ResourceManager.GetString("HexagramBi_ShanHuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 山地剝.
        /// </summary>
        internal static string HexagramBo {
            get {
                return ResourceManager.GetString("HexagramBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 澤地萃.
        /// </summary>
        internal static string HexagramCui {
            get {
                return ResourceManager.GetString("HexagramCui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 澤風大過.
        /// </summary>
        internal static string HexagramDaGuo {
            get {
                return ResourceManager.GetString("HexagramDaGuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 山天大畜.
        /// </summary>
        internal static string HexagramDaXu {
            get {
                return ResourceManager.GetString("HexagramDaXu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火天大有.
        /// </summary>
        internal static string HexagramDaYou {
            get {
                return ResourceManager.GetString("HexagramDaYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷天大壯.
        /// </summary>
        internal static string HexagramDaZhuang {
            get {
                return ResourceManager.GetString("HexagramDaZhuang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火風鼎.
        /// </summary>
        internal static string HexagramDing {
            get {
                return ResourceManager.GetString("HexagramDing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兌為澤.
        /// </summary>
        internal static string HexagramDui {
            get {
                return ResourceManager.GetString("HexagramDui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天山遁.
        /// </summary>
        internal static string HexagramDun {
            get {
                return ResourceManager.GetString("HexagramDun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷火豐.
        /// </summary>
        internal static string HexagramFeng {
            get {
                return ResourceManager.GetString("HexagramFeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地雷復.
        /// </summary>
        internal static string HexagramFu {
            get {
                return ResourceManager.GetString("HexagramFu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 澤火革.
        /// </summary>
        internal static string HexagramGe {
            get {
                return ResourceManager.GetString("HexagramGe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艮為山.
        /// </summary>
        internal static string HexagramGen {
            get {
                return ResourceManager.GetString("HexagramGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天風姤.
        /// </summary>
        internal static string HexagramGou {
            get {
                return ResourceManager.GetString("HexagramGou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 山風蠱.
        /// </summary>
        internal static string HexagramGu {
            get {
                return ResourceManager.GetString("HexagramGu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 澤天夬.
        /// </summary>
        internal static string HexagramGuai {
            get {
                return ResourceManager.GetString("HexagramGuai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 風地觀.
        /// </summary>
        internal static string HexagramGuan {
            get {
                return ResourceManager.GetString("HexagramGuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷澤歸妹.
        /// </summary>
        internal static string HexagramGuiMei {
            get {
                return ResourceManager.GetString("HexagramGuiMei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷風恆.
        /// </summary>
        internal static string HexagramHeng {
            get {
                return ResourceManager.GetString("HexagramHeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 風水渙.
        /// </summary>
        internal static string HexagramHuan {
            get {
                return ResourceManager.GetString("HexagramHuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 風山漸.
        /// </summary>
        internal static string HexagramJian {
            get {
                return ResourceManager.GetString("HexagramJian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水山蹇.
        /// </summary>
        internal static string HexagramJian_ShuiShan {
            get {
                return ResourceManager.GetString("HexagramJian_ShuiShan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 風火家人.
        /// </summary>
        internal static string HexagramJiaRen {
            get {
                return ResourceManager.GetString("HexagramJiaRen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷水解.
        /// </summary>
        internal static string HexagramJie {
            get {
                return ResourceManager.GetString("HexagramJie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水澤節.
        /// </summary>
        internal static string HexagramJie_ShuiZe {
            get {
                return ResourceManager.GetString("HexagramJie_ShuiZe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水火既濟.
        /// </summary>
        internal static string HexagramJiJi {
            get {
                return ResourceManager.GetString("HexagramJiJi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火地晉.
        /// </summary>
        internal static string HexagramJin {
            get {
                return ResourceManager.GetString("HexagramJin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水風井.
        /// </summary>
        internal static string HexagramJing {
            get {
                return ResourceManager.GetString("HexagramJing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 坎為水.
        /// </summary>
        internal static string HexagramKan {
            get {
                return ResourceManager.GetString("HexagramKan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火澤睽.
        /// </summary>
        internal static string HexagramKui {
            get {
                return ResourceManager.GetString("HexagramKui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 澤水困.
        /// </summary>
        internal static string HexagramKun {
            get {
                return ResourceManager.GetString("HexagramKun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 坤為地.
        /// </summary>
        internal static string HexagramKun_WeiDi {
            get {
                return ResourceManager.GetString("HexagramKun_WeiDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 離為火.
        /// </summary>
        internal static string HexagramLi {
            get {
                return ResourceManager.GetString("HexagramLi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地澤臨.
        /// </summary>
        internal static string HexagramLin {
            get {
                return ResourceManager.GetString("HexagramLin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天澤履.
        /// </summary>
        internal static string HexagramLv {
            get {
                return ResourceManager.GetString("HexagramLv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火山旅.
        /// </summary>
        internal static string HexagramLv_Travel {
            get {
                return ResourceManager.GetString("HexagramLv_Travel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 山水蒙.
        /// </summary>
        internal static string HexagramMeng {
            get {
                return ResourceManager.GetString("HexagramMeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地火明夷.
        /// </summary>
        internal static string HexagramMingYi {
            get {
                return ResourceManager.GetString("HexagramMingYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天地否.
        /// </summary>
        internal static string HexagramPi {
            get {
                return ResourceManager.GetString("HexagramPi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乾為天.
        /// </summary>
        internal static string HexagramQian {
            get {
                return ResourceManager.GetString("HexagramQian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地山謙.
        /// </summary>
        internal static string HexagramQian_DiShan {
            get {
                return ResourceManager.GetString("HexagramQian_DiShan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地風升.
        /// </summary>
        internal static string HexagramSheng {
            get {
                return ResourceManager.GetString("HexagramSheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地水師.
        /// </summary>
        internal static string HexagramShi {
            get {
                return ResourceManager.GetString("HexagramShi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火雷噬嗑.
        /// </summary>
        internal static string HexagramShiKe {
            get {
                return ResourceManager.GetString("HexagramShiKe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天水訟.
        /// </summary>
        internal static string HexagramSong {
            get {
                return ResourceManager.GetString("HexagramSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 澤雷隨.
        /// </summary>
        internal static string HexagramSui {
            get {
                return ResourceManager.GetString("HexagramSui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 山澤損.
        /// </summary>
        internal static string HexagramSun {
            get {
                return ResourceManager.GetString("HexagramSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地天泰.
        /// </summary>
        internal static string HexagramTai {
            get {
                return ResourceManager.GetString("HexagramTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天火同人.
        /// </summary>
        internal static string HexagramTongRen {
            get {
                return ResourceManager.GetString("HexagramTongRen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水雷屯.
        /// </summary>
        internal static string HexagramTun {
            get {
                return ResourceManager.GetString("HexagramTun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火水未濟.
        /// </summary>
        internal static string HexagramWeiJi {
            get {
                return ResourceManager.GetString("HexagramWeiJi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天雷無妄.
        /// </summary>
        internal static string HexagramWuWang {
            get {
                return ResourceManager.GetString("HexagramWuWang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 澤山咸.
        /// </summary>
        internal static string HexagramXian {
            get {
                return ResourceManager.GetString("HexagramXian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷山小過.
        /// </summary>
        internal static string HexagramXiaoGuo {
            get {
                return ResourceManager.GetString("HexagramXiaoGuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 風天小畜.
        /// </summary>
        internal static string HexagramXiaoXu {
            get {
                return ResourceManager.GetString("HexagramXiaoXu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水天需.
        /// </summary>
        internal static string HexagramXu {
            get {
                return ResourceManager.GetString("HexagramXu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 巽為風.
        /// </summary>
        internal static string HexagramXun {
            get {
                return ResourceManager.GetString("HexagramXun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 風雷益.
        /// </summary>
        internal static string HexagramYi {
            get {
                return ResourceManager.GetString("HexagramYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 山雷頤.
        /// </summary>
        internal static string HexagramYi_ShanLei {
            get {
                return ResourceManager.GetString("HexagramYi_ShanLei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷地豫.
        /// </summary>
        internal static string HexagramYu {
            get {
                return ResourceManager.GetString("HexagramYu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 震為雷.
        /// </summary>
        internal static string HexagramZhen {
            get {
                return ResourceManager.GetString("HexagramZhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 風澤中孚.
        /// </summary>
        internal static string HexagramZhongFu {
            get {
                return ResourceManager.GetString("HexagramZhongFu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分類占斷.
        /// </summary>
        internal static string HexgramJudgeClassfied {
            get {
                return ResourceManager.GetString("HexgramJudgeClassfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主占斷.
        /// </summary>
        internal static string HexgramJudgement {
            get {
                return ResourceManager.GetString("HexgramJudgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卦辭.
        /// </summary>
        internal static string HexgramMain {
            get {
                return ResourceManager.GetString("HexgramMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梅花易術.
        /// </summary>
        internal static string HexGramMeihua {
            get {
                return ResourceManager.GetString("HexGramMeihua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偈語.
        /// </summary>
        internal static string HexgramPoem {
            get {
                return ResourceManager.GetString("HexgramPoem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卦象.
        /// </summary>
        internal static string HexgramSymbol {
            get {
                return ResourceManager.GetString("HexgramSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卦數.
        /// </summary>
        internal static string HexgramSymbolNumber {
            get {
                return ResourceManager.GetString("HexgramSymbolNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 體用比和.
        /// </summary>
        internal static string InternalExternalSame {
            get {
                return ResourceManager.GetString("InternalExternalSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 體生用.
        /// </summary>
        internal static string InternalGeneratesExternal {
            get {
                return ResourceManager.GetString("InternalGeneratesExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 體克用.
        /// </summary>
        internal static string InternalOvercomesExternal {
            get {
                return ResourceManager.GetString("InternalOvercomesExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 這是一個易經占蔔工具。
        ///
        ///[即時起卦]：用當前時間起卦。由於一天共分十二個時辰，因此在同一天同一時辰所起的卦是相同的。
        ///
        ///[隨機起卦]：用隨機數生成卦。
        ///
        ///[卦辭]，[卦象]以及其它選項從不同角度解釋所得卦之含義。其中[梅花易數]為動態生成用於預測吉兇和時間。除[梅花易數]外各項解釋均引自易經原文和互聯網絡。
        ///
        ///作者：彭晟 Sam Peng
        ///聯系：sam.s.peng@gmail.com.
        /// </summary>
        internal static string MainHelp {
            get {
                return ResourceManager.GetString("MainHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 易經占蔔.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兌.
        /// </summary>
        internal static string TrigramDui {
            get {
                return ResourceManager.GetString("TrigramDui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艮.
        /// </summary>
        internal static string TrigramGen {
            get {
                return ResourceManager.GetString("TrigramGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 坎.
        /// </summary>
        internal static string TrigramKan {
            get {
                return ResourceManager.GetString("TrigramKan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 坤.
        /// </summary>
        internal static string TrigramKun {
            get {
                return ResourceManager.GetString("TrigramKun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 離.
        /// </summary>
        internal static string TrigramLi {
            get {
                return ResourceManager.GetString("TrigramLi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乾.
        /// </summary>
        internal static string TrigramQian {
            get {
                return ResourceManager.GetString("TrigramQian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地.
        /// </summary>
        internal static string TrigramSymbolEarth {
            get {
                return ResourceManager.GetString("TrigramSymbolEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天.
        /// </summary>
        internal static string TrigramSymbolHeaven {
            get {
                return ResourceManager.GetString("TrigramSymbolHeaven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 澤.
        /// </summary>
        internal static string TrigramSymbolLake {
            get {
                return ResourceManager.GetString("TrigramSymbolLake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 山.
        /// </summary>
        internal static string TrigramSymbolMountain {
            get {
                return ResourceManager.GetString("TrigramSymbolMountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷.
        /// </summary>
        internal static string TrigramSymbolThunder {
            get {
                return ResourceManager.GetString("TrigramSymbolThunder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 風.
        /// </summary>
        internal static string TrigramSymbolWind {
            get {
                return ResourceManager.GetString("TrigramSymbolWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 巽.
        /// </summary>
        internal static string TrigramXun {
            get {
                return ResourceManager.GetString("TrigramXun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 震.
        /// </summary>
        internal static string TrigramZhen {
            get {
                return ResourceManager.GetString("TrigramZhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下.
        /// </summary>
        internal static string WordDown {
            get {
                return ResourceManager.GetString("WordDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上.
        /// </summary>
        internal static string WordUp {
            get {
                return ResourceManager.GetString("WordUp", resourceCulture);
            }
        }
    }
}
